### ISSUE TITLE
Что надо пофиксить в Board(на первый взгляд)

### ISSUE THREAD

**Issue by shirokov-kirill** [shirokov-kirill/Naval_battle_project#14]
Нигде не обрабатывается добавление корабля(working_ships не увеличивается), отсюда идёт бага в функции is_alive() и далее. Так как у нас высота--X, а глубина--Y, в функции place_ship() перепутаны вертикальное и горизонтальное положения(возможно они перепутаны ещё где-то, в теории желательно, чтобы проходило все тесты). can_place_ship() кидает постоянно Segfault, явно что-то не так.

**Comment by KreslavskiKD** [comment]
all fixed
