### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by KreslavskiKD** [shirokov-kirill/Naval_battle_project#3]
Some changes to the list of methods of Player and Controller

**Comment by shirokov-kirill** [comment]
Added: Player: std::string name;--новое поле
                        void set_name(std::string);--метод
                        bool is_alive();--метод
                        bool can_shoot(int, int);--метод
            Controller: Player players[] -> std::vector<Player> players;
                              std::vector<Player>winners;--новое поле
To add in others:  Interface: std::string read_name(int)--вернуть имя по номеру
                                            void show_error(std::string)--вывести ошибку на экран
                            Board: если функция shoot() делает поле visible  и обрабатывает потопление и тд, то всё ок, иначе добавить функцию  bool is_sunk(int, int) и decr_working_ships();
