### ISSUE TITLE
Расстановка горизонтальных кораблей

### ISSUE THREAD

**Issue by yakovleval** [shirokov-kirill/Naval_battle_project#8]
Если горизонтальный корабль упирается в правую (для меня) стенку, то функция `can_place_ship()` ловит сегфолт

**Comment by KreslavskiKD** [comment]
упирается началом или концом? или чем?

**Comment by yakovleval** [comment]
упирается концом (если за начало считать ту клетку, которую принимает функция `place_ship`)

**Comment by KreslavskiKD** [comment]
fixed
